om_auth:
    resource: "@OMAuthBundle/Resources/config/routing.yml"
    prefix:   /

om_administration:
    resource: "@OMAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

om_localisation:
    resource: "@OMLocalisationBundle/Resources/config/routing.yml"
    prefix:   /

om_espace_user:
    resource: "@OMEspaceUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    methods:  [GET, POST, OPTIONS]


user_api_demos:
    type: rest
    resource: OM\EspaceUserBundle\Controller\DemoController

#test_rest
test:
    resource: "@OMAdministrationBundle/Controller/DefaultController.php"
    prefix:   /
    type:     rest
#user
user:
    resource: "@OMEspaceUserBundle/Controller/UserController.php"
    prefix:   /
    type:     rest
#register
signup:
    resource: "@OMEspaceUserBundle/Controller/RegistrationController.php"
    prefix:   /
    type:     rest
#session
session:
    resource: "@OMAuthBundle/Controller/SessionController.php"
    prefix:   /
    type:     rest

