om_administration:
    resource: "@OMAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

om_localisation:
    resource: "@OMLocalisationBundle/Resources/config/routing.yml"
    prefix:   /

om_espace_user:
    resource: "@OMEspaceUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#tag rest
tag:
    resource: "@OMAdministrationBundle/Controller/TagController.php"
    prefix:   /
    type:     rest