security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_PROSPECT:    ROLE_PROSPECT
        ROLE_WORKER:      ROLE_WORKER
        ROLE_MONITOR:     ROLE_MONITOR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/client/, role: ROLE_CLIENT }
        - { path: ^/prospect/, role: ROLE_PROSPECT }
        - { path: ^/worker/, role: ROLE_WORKER }
        - { path: ^/monitor/, role: ROLE_MONITOR }